### PR TITLE
add: function to return machine pool labels

### PR DESCRIPTION
**Pull request by VanillaSpoon**
# Issue link
Adding this function to use when updating machinepool tests for this [pr](https://github.com/project-codeflare/instascale/pull/182)

# What changes have been made
Addition of a label that returns if a machinepool contains a specified label key.

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by Fiona-Waters — COMMENTED** [review]
/lgtm

**Comment by sutaakar** [comment]
@VanillaSpoon I am not much a fan of test functions returning bool.
What is the use case you want to use it in?

**Comment by VanillaSpoon** [comment]
Hi @sutaakar,
Thanks for the question. I was hoping to use the function with this [pr](https://github.com/project-codeflare/codeflare-operator/pull/413/commits/c4c9068dfe91462c88817fd6c617ccb60bbb5277). Checking for the existence of a machinepool with a label key matching the appwrapper used to scale up, before and after.

Although, if there is a preferred method, I am happy to update :)

**Comment by VanillaSpoon** [comment]
> @VanillaSpoon The problem with bool comparison like:
> 
> ```
> 	test.Expect(GetMachinePools(test, connection)).
> 		Should(ContainElement(WithTransform(
> 			func(machinePool *cmv1.MachinePool) bool {
> 				return MachinePoolHasLabelKey(machinePool, "test-instascale")
> 			},
> 			BeFalse(),
> 		)))
> ```
> 
> is that in case of failure you get error message like "true is not false", which doesn't say much.
> 
> Better approach is to test for specific value. So in this case it should be better to check list of keys, like (code untested):
> 
> ```
> 	test.Expect(GetMachinePools(test, connection)).
> 		Should(ContainElement(WithTransform(MachinePoolLabelKeys, ContainElement("test-instascale"))))
> ```
> 
> while `MachinePoolLabelKeys` will return a slice of keys.
> 
> What do you think?

Ooohhh I see! Thanks for the clarification, I can see how that's a hindrance.

 I love it :) I'll make the adjustments now

**Review by sutaakar — COMMENTED** [review]
/lgtm

**Pull request merged**
